<?xml version="1.0"?>
<package format="3">

  <name>bot_description</name>
  <version>0.0.1</version>

  <description>6 DOF Robot Arm Description</description>

  <maintainer email="user@todo.com">user</maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>robot_state_publisher</depend>
  <depend>joint_state_publisher_gui</depend>
  <depend>rviz2</depend>
  <depend>xacro</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
